style: try another workflow

diff --git a/.github/workflows/format.yml b/.github/workflows/format.yml
--- a/.github/workflows/format.yml
+++ b/.github/workflows/format.yml
@@ -1,28 +1,56 @@
-name: cpp-linter
+name: Clang-Format Lint Check
+
 on:
   pull_request:
-    branches: [ main ]
+    types: [opened, synchronize, reopened]
 
 jobs:
-  cpp-linter:
+  clang-format-check:
     runs-on: ubuntu-latest
-    permissions:
-      pull-requests: write
-    
+
     steps:
-      - uses: actions/checkout@v4
-      - uses: cpp-linter/cpp-linter-action@v2
-        id: linter
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Install clang-format
+        run: sudo apt-get update && sudo apt-get install -y clang-format-19
+
+      - name: Find unformatted files
+        id: format_check
+        run: |
+          FILE_LIST="unformatted_files.txt"
+          find src ! -path 'src/third_party/*' \
+            -regex '.*\.\(cpp\|hpp\|h\|c\|cc\|cu\|cuh\)' \
+            -exec bash -c 'clang-format-19 -style=file -output-replacements-xml "$0" | grep -q "<replacement " && echo "$0"' {} \; > "$FILE_LIST"
+          cat "$FILE_LIST"
+          if [ -s "$FILE_LIST" ]; then
+            {
+              echo 'files<<EOF'
+              cat "$FILE_LIST"
+              echo 'EOF'
+            } >> "$GITHUB_OUTPUT"
+          else
+            echo 'files=' >> "$GITHUB_OUTPUT"
+          fi          
+
+      - name: Comment on PR if formatting issues found
+        if:  steps.format_check.outputs.files != ''
+        uses: peter-evans/create-or-update-comment@v4
         with:
-          style: 'file'  # Use .clang-format config file. 
-          tidy-checks: '-*' # disable clang-tidy checks.
-          extensions: 'cu,cuh,c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx'
-          files-changed-only: false
-          # only 'update' a single comment in a pull request's thread. 
-          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
-          
-      - name: Fail fast?!
-        if: steps.linter.outputs.clang-format-checks-failed > 0
-        run: exit 1
+          issue-number: ${{ github.event.pull_request.number }}
+          body: |
+            ⚠️ **Clang-format check failed**
+            
+            The following files are not correctly formatted:
+            ```
+            "${{ steps.format_check.outputs.files }}"
+            ```
+            Please run `clang-format -i` on these files and commit the changes  before merging.
+            
+
+      - name: Fail job if formatting issues found
+        if: steps.format_check.outputs.files != ''
+        run: |
+          echo "Formatting issues detected. Failing the job."
+          exit 1
+       
